services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: StoreManagement
      POSTGRES_USER: TarikKartal
      POSTGRES_PASSWORD: TarikKartalPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
